/**
 * Seeds ~10,000 todos with a realistic spread (R-6.3 verification data):
 * weighted statuses, mixed priorities, due dates across ±90 days, ~10%
 * recurring, ~5% soft-deleted, and ~1,500 dependency edges arranged in
 * clusters. Edges always point from a later row to an earlier one, so the
 * graph is acyclic by construction.
 *
 * Run: npm run db:seed   (uses DATABASE_URL)
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const TOTAL = 10_000;
const BATCH = 1_000;

const VERBS = ["Review", "Draft", "Deploy", "Fix", "Update", "Design", "Test", "Migrate", "Audit", "Refactor"];
const NOUNS = ["billing flow", "landing page", "API docs", "user survey", "release notes", "onboarding", "dashboard", "backup job", "search index", "ad campaign"];

const pick = <T>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)]!;
const weighted = <T>(pairs: Array<[T, number]>): T => {
  const r = Math.random() * pairs.reduce((s, [, w]) => s + w, 0);
  let acc = 0;
  for (const [value, w] of pairs) {
    acc += w;
    if (r < acc) return value;
  }
  return pairs[pairs.length - 1]![0];
};

async function main() {
  const existing = await prisma.todo.count();
  if (existing > 1000) {
    console.log(`Database already has ${existing} todos — skipping seed.`);
    return;
  }

  const now = Date.now();
  const DAY = 24 * 3600 * 1000;
  const ids: string[] = [];
  const statuses: string[] = [];

  for (let batch = 0; batch < TOTAL / BATCH; batch++) {
    const rows = Array.from({ length: BATCH }, (_, i) => {
      const n = batch * BATCH + i;
      const status = weighted([
        ["not_started", 40],
        ["in_progress", 15],
        ["completed", 35],
        ["archived", 10],
      ] as const);
      const dueOffset = Math.floor(Math.random() * 180) - 90; // ±90 days
      const id = crypto.randomUUID();
      ids.push(id);
      statuses.push(status);
      return {
        id,
        name: `${pick(VERBS)} ${pick(NOUNS)} #${n}`,
        description: Math.random() < 0.5 ? `Autogenerated seed item ${n}` : null,
        status,
        priority: weighted([
          ["low", 30],
          ["medium", 45],
          ["high", 25],
        ] as const),
        dueDate: Math.random() < 0.8 ? new Date(now + dueOffset * DAY) : null,
        recurrence:
          Math.random() < 0.1
            ? {
                frequency: pick(["daily", "weekly", "monthly"]),
                interval: pick([1, 1, 1, 2, 3]),
              }
            : undefined,
        deletedAt: Math.random() < 0.05 ? new Date(now - Math.random() * 30 * DAY) : null,
      };
    });
    await prisma.todo.createMany({ data: rows });
    // The service layer writes a `created` activity with every insert; seeded
    // rows must tell the same story or their timelines start mid-life.
    await prisma.activity.createMany({
      data: rows.map((r) => ({
        todoId: r.id,
        type: "created",
        payload: {
          name: r.name,
          priority: r.priority,
          dueDate: r.dueDate?.toISOString() ?? null,
          recurrence: r.recurrence ?? null,
        },
      })),
    });
    console.log(`Seeded todos ${batch * BATCH + 1}–${(batch + 1) * BATCH}`);
  }

  // Dependency clusters: each edge points backwards (dependent is a later
  // row than its dependency) → acyclic. Only live todos get edges (R-1.4).
  const edges: Array<{ dependentId: string; dependencyId: string }> = [];
  const seen = new Set<string>();
  const live = (i: number) => statuses[i] !== undefined; // all rows exist; deleted filtered below

  for (let e = 0; e < 1_500; e++) {
    const dependentIdx = 1 + Math.floor(Math.random() * (TOTAL - 1));
    const dependencyIdx = Math.floor(Math.random() * dependentIdx); // strictly earlier
    if (!live(dependentIdx) || !live(dependencyIdx)) continue;
    // Only combinations the API itself can produce (A11 + A13): a started or
    // finished dependent can only sit on a COMPLETED dependency.
    const dependentStatus = statuses[dependentIdx]!;
    const dependencyStatus = statuses[dependencyIdx]!;
    if (
      (dependentStatus === "in_progress" || dependentStatus === "completed") &&
      dependencyStatus !== "completed"
    ) {
      continue;
    }
    const key = `${dependentIdx}:${dependencyIdx}`;
    if (seen.has(key)) continue;
    seen.add(key);
    edges.push({ dependentId: ids[dependentIdx]!, dependencyId: ids[dependencyIdx]! });
  }
  // Edges must reference live todos only
  const deleted = new Set(
    (await prisma.todo.findMany({ where: { deletedAt: { not: null } }, select: { id: true } })).map(
      (t) => t.id
    )
  );
  const liveEdges = edges.filter((e) => !deleted.has(e.dependentId) && !deleted.has(e.dependencyId));
  await prisma.todoDependency.createMany({ data: liveEdges, skipDuplicates: true });

  // Same story-consistency rule for the edges: one dependencies_changed
  // activity per dependent, names snapshotted like the service does.
  const nameById = new Map(
    (await prisma.todo.findMany({ select: { id: true, name: true } })).map((t) => [t.id, t.name])
  );
  const byDependent = new Map<string, string[]>();
  for (const e of liveEdges) {
    const list = byDependent.get(e.dependentId);
    if (list) list.push(e.dependencyId);
    else byDependent.set(e.dependentId, [e.dependencyId]);
  }
  await prisma.activity.createMany({
    data: [...byDependent.entries()].map(([dependentId, depIds]) => ({
      todoId: dependentId,
      type: "dependencies_changed",
      payload: {
        added: depIds.map((d) => ({ id: d, name: nameById.get(d) ?? "?" })),
        removed: [],
      },
    })),
  });
  console.log(`Seeded ${liveEdges.length} dependency edges`);

  console.log(`Done: ${await prisma.todo.count()} todos.`);
}

main().finally(() => prisma.$disconnect());
